// config/planFeatures.js

const planFeatures = {
  free: {
    annually: {
      price: 0,
      features: [
        "For 1 queue and 1 user",
        "Single queue management",
        "50 tickets/day",
        "Queue management dashboard",
        "Two Services",
        "Access to RightQ mobile apps",
        "Counter/Area management",
        "Client management",
        "Device management",
        "Digital signage powered by RightPlayer",
        "Customer satisfaction powered by RightSurvey",
        "Reports & analytics",
        "Real-time notifications",
        "Free support",
      ],
    },
    monthly: {
      price: 0,
      features: [
        "For 1 queue and 1 user",
        "50 tickets/day",
        "Queue management dashboard",
        "Two services",
        "Access to RightQ mobile apps",
        "Counter/Zone management",
        "Client management",
        "Device management",
        "Digital signage powered by RightPlayer",
        "Customer satisfaction powered by RightSurvey",
        "Reports & analytics",
        "Real-time notifications",
        "Free support",
      ],
    },
  },
  lite: {
    annually: {
      price: 30,
      features: [
        "Everything in Free +",
        "For 1 queue and 5 users*",
        "Multi-queue management",
        "Multi-location",
        "150 tickets/day/queue",
        "Six services",
        "Service management",
        "User & role management",
        "Role-based dashboard (Agent, Manager, Admin)",
        "Virtual ticket dispenser (Web, QR Code, Social Media)",
      ],
    },
    monthly: {
      price: 50,
      features: [
        "Everything in Free +",
        "For 1 queue and 5 users*",
        "Multi-queue management",
        "Multi-location",
        "150 tickets/day/queue",
        "Six services",
        "Service management",
        "Role-based dashboard (Agent, Manager, Admin)",
        "Virtual ticket dispenser (Web, QR Code, Social Media)",
        "Virtual waiting room",
      ],
    },
  },
  pro: {
    annually: {
      price: 250,
      features: [
        "Everything in Lite",
        "For 1 queue and 10 users**",
        "Unlimited tickets",
        "Unlimited services",
        "Advanced client management",
        "Workflow & automation",
        "Advanced reports & analytics",
        "Performance email report",
        "SLA management",
        "Integration (SMS, USSD, Chatbot)***",
      ],
    },
  },
  team: {
    annually: {
      price: 100,
      features: [
        "Everything in Pro +",
        "10,000 responses per month*",
        "5 users**",
        "Team collaboration",
        "Unlimited projects",
        "Unlimited user groups",
        "User & role management",
        "Chatbot survey with RightBot",
        "Smart Notifications",
        "Pre-built workflows with RightDesk, RightQ, RightTime, RightData, RightFlow, and RightPlayer",
        "Premium integrations including Salesforce, Hubspot, Slack, Intercom, Microsoft Teams, and Mailchimp",
        "Premium Support",
      ],
    },
    monthly: {
      price: 0,
      features: [
        "Everything in Pro",
        "10,000 responses per month*",
        "5 users*",
        "Team collaboration",
        "Unlimited projects",
        "Unlimited user groups",
        "User & role management",
        "Chatbot survey with RightBot",
        "Smart Notifications",
        "Pre-built workflows with RightDesk, RightQ, RightTime, RightData, RightFlow, and RightPlayer",
        "Premium integrations including Salesforce, Hubspot, Slack, Intercom, Microsoft Teams, and Mailchimp",
        "Premium Support",
      ]
    },
  },
  enterprise: {
    annually: {
      price: "Contact us",
      features: [
        "Everything in Pro",
        "Unlimited users",
        "Custom reports & dashboards",
        "Custom billing",
        "Audit log",
        "Custom integrations (CRM, marketing, billing, support, etc.)",
        "Custom security policy",
        "Dedicated customer success manager",
      ],
    },
  },
};

module.exports = planFeatures;